version: '3'
services:
  client:
    build: ./client
    volumes:
      - ./client:/app/
      - client_modules:/app/node_modules
    ports:
      - "5000:5000"
  server:
    build: ./server
    volumes:
      - ./server:/app/
      - server_modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  client_modules:
  server_modules: